9451/program support
AcclaroInc/craft-translations pull request #511
Opened 2024-08-21 13:33 UTC by sharmarishabh1

## Pull Request

### Description:
 Added the support for adding programs to orders with translator service as "acclaro"

### Changes Made:

**Added:**

 - Drop down selection to enable "addToProgram" for a translator service.
 - Drop down selection to choose from the programs enabled for the selected translator

### Testing:
 - Created orders with different programs
 - Created orders with and without programs 
 - Changing a program in Acclaro reflects on the plugin 

### Quality Assurance (QA):

- [ ] The code has been reviewed and approved by the QA team.
- [ ] The changes have been tested on different environments (e.g., staging, production).
- [ ] Integration tests have been performed to verify the interactions between components.
- [ ] Performance tests have been conducted to ensure the changes do not impact system performance.
- [ ] Any necessary database migrations or data transformations have been executed successfully.
- [ ] Accessibility requirements have been considered and tested (e.g., screen reader compatibility, keyboard navigation).

### Resources:

**Screenshots **

Changes on the translator settings page:

![image](https://github.com/user-attachments/assets/c5eaea28-52ab-4d97-952a-a4c3eb74007a)

Changes on the order creation page:

![image](https://github.com/user-attachments/assets/6d6bf595-2cb3-4a7e-a419-3ff77a9880c2)

### Wrapping up

**Checklist:**

- [ ] The code builds without any errors or warnings.
- [ ] The code follows the project's coding conventions and style guidelines.
- [ ] Unit tests have been added or updated to cover the changes made.
- [ ] The documentation has been updated to reflect the changes (if applicable).
- [ ] All new and existing tests pass successfully.
- [ ] The PR has been reviewed by at least one other team member.

**Additional Notes:**
[Include any additional notes, considerations, or context that may be relevant.]

2024-08-22 06:17 UTC, sidedwards requested changes
@sharmarishabh1 let's change "Add to program" to "Enable Programs" and add it to an advanced options section.

2024-08-22 11:52 UTC, sharmarishabh1 commented
Hi @sidedwards 
As per the initial discussion with @bhupeshappfoster on this feature, he was sharing that "contentful" follows the same pattern i.e. it has the "add to program" outside the advanced settings bar and since we are trying to keep it similar to it - I went forward and did the same. 

It would be great if you could confirm how would we like it move ahead on it once 

 > let's change "Add to program" to "Enable Programs
Do we want this change to come up on both the pages or just the translator settings page?

Let me know if you need more information on this. 

Thanks!

cc @shnsumit

2024-08-26 05:37 UTC, bhupeshappfoster commented
@sharmarishabh1 

Lets go with what @sidedwards suggested here, will later on change it if required.

2024-08-28 16:05 UTC, shnsumit approved these changes

2024-08-28 17:56 UTC, sidedwards approved these changes

2024-08-29 08:52 UTC, merged